title: SciSoc Agents & LLMs Workshop
description:  KDD'26 Workshop on SciSoc Agents & LLMs
url: "https://KDD26SciSocLLM.github.io"
baseurl: ""

markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

social:
  email: representational-alignment@googlegroups.com
